import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  section: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginHorizontal: 20,
    marginTop: 16,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#aaa",
    paddingTop: 16,
    paddingBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  infoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(45,198,160,0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: "#aaa",
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 15,
    color: "#333",
    fontWeight: "500",
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingVertical: 12,
    gap: 8,
  },
  tag: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(45,198,160,0.12)",
    borderWidth: 1,
    borderColor: "#2DC6A0",
  },
  tagDanger: {
    backgroundColor: "rgba(231,76,60,0.08)",
    borderColor: "#e74c3c",
  },
  tagText: {
    fontSize: 13,
    color: "#2DC6A0",
    fontWeight: "600",
  },
  tagTextDanger: {
    color: "#e74c3c",
  },
  addTagBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#ddd",
    borderStyle: "dashed",
  },
  addTagText: {
    fontSize: 13,
    color: "#aaa",
  },
  editBtn: {
    backgroundColor: "#2DC6A0",
    borderRadius: 14,
    marginHorizontal: 20,
    marginTop: 24,
    marginBottom: 40,
    paddingVertical: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  editBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#222",
    marginBottom: 20,
    textAlign: "center",
  },
  modalInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  modalInputFocused: {
    borderColor: "#2DC6A0",
    backgroundColor: "rgba(45,198,160,0.06)",
  },
  modalInput: {
    flex: 1,
    color: "#333",
    fontSize: 15,
    marginLeft: 10,
  },
  modalSaveBtn: {
    backgroundColor: "#2DC6A0",
    borderRadius: 50,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
  },
  modalSaveBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  modalCancelBtn: {
    borderRadius: 50,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  modalCancelBtnText: {
    color: "#aaa",
    fontSize: 15,
  },
});